name: WaveFighter
version: '1.0-SNAPSHOT'
main: zintis.id.lv.waveFighter.WaveFighter
api-version: '1.21'
commands:
  startwave:
    description: "Start Wave"
    usage: "/startwave"
  wavekits:
    description: "Get a List of Usable Kits for WaveFigther Mini-Game"
    usage: "/wavekits"
  wavekit:
    description: "Choose a Kit For WaveFigther Mini-Game"
    usage: "/wavekit"
